package:
  name: fenics-components
  version: 2008.1.0

build:
  number: 0
  features:
    - tue

requirements:
  build:
    - python {{ python }}

  run:
    - libgfortran 3.0.0  1
    - numpy
    - openblas    0.2.20 6
    - python {{ python }}
    - tue

test:
  imports:
    - instant
    - FIAT
    - ffc
    - ufc

  commands:
    - conda inspect linkages fenics-components
