package:
  name: dijitso
  version: "2017.1.0"

source:
  url: https://bitbucket.org/fenics-project/dijitso/downloads/dijitso-2017.1.0.tar.gz
  sha256: ef23952539d349fbd384d41302abc94413d485ca7e8c29e8a0debc2aadaf8657

build:
  number: 0
  string: py{{ CONDA_PY }}_tue_{{ PKG_BUILDNUM }}

requirements:
  build:
    - python {{ python }}
    - six
    - numpy
    - subprocess32  # [py2k]

  run:
    - python {{ python }}
    - six
    - numpy
    - subprocess32  # [py2k]

test:
  imports:
    - dijitso
