blacs:     blacs          1.1
hdf5:      hdf5           1.8.20
hypre:     hypre          2.11.2
mumps:     mumps          5.1.2
openmpi:   openmpi        2.1.2     *_7
petsc:     petsc          3.8.1
scalapack: scalapack      2.0.2
scotch:    scotch         6.0.4
dijitso:   fenics-dijitso 2017.1.0
dolfin:    fenics-dolfin  2017.1.0
ffc:       fenics-ffc     2017.1.0
fiat:      fenics-fiat    2017.1.0
instant:   fenics-instant 2017.1.0
mshr:      fenics-mshr    2017.1.0
ufl:       fenics-ufl     2017.1.0
python:
  - 2.7
  - 3.5
