package:
  name: fenics-fiat
  version: 2017.1.0

source:
  url: https://bitbucket.org/fenics-project/fiat/downloads/fiat-2017.1.0.tar.gz
  sha256: d4288401ad16c4598720f9db0810a522f7f0eadad35d8211bac7120bce5fde94

build:
  number: 2

requirements:
  build:
    - python {{ python }}

  run:
    - python {{ python }}
    - six
    - numpy
    - nomkl
    - sympy

test:
  imports:
    - FIAT

  commands:
    - conda inspect linkages fenics-fiat
