package:
  name: fenics-fiat
  version: 2017.2.0

source:
  url: https://bitbucket.org/fenics-project/fiat/downloads/fiat-2017.2.0.tar.gz
  sha256: abf4bfae6ab67601ab49e6df1ee3664c19c36f18467720706ec9e62d4c75837c

build:
  number: 0

requirements:
  build:
    - python {{ python }}

  run:
    - python {{ python }}
    - six
    - numpy
    - sympy

test:
  imports:
    - FIAT

  commands:
    - conda inspect linkages fenics-fiat
