package:
  name: fenics-fiat
  version: 2018.1.0

source:
  url: https://bitbucket.org/fenics-project/fiat/downloads/fiat-2018.1.0.tar.gz
  sha256: 3d897d99fdc94441f9c8720fb5a3bcaf8a0b9ede897a0600cb1f329dacec5c92

build:
  number: 0

requirements:
  build:
    - python {{ python }}

  run:
    - python {{ python }}
    - six
    - numpy
    - sympy

test:
  imports:
    - FIAT

  commands:
    - conda inspect linkages fenics-fiat
