#!/bin/bash
#
# Shortcut/alias to conda-build with proper options.

PREFIX="${HOME}/fenics-tue/conda"

bash check_internet.sh
if [ "${?}" != "0" ]; then
  if [ "$(hostname -s)" == "rng" ] || [ "$(hostname -s)" == "furnace" ]; then
    export http_proxy="http://proxy.wfw.wtb.tue.nl:80"
    export https_proxy="https://proxy.wfw.wtb.tue.nl:443"
  else
    echo "No internet connectivity available."
    exit 1
  fi
fi

if [ "${1}" == "purge" ]; then
  "${PREFIX}/conda/bin/conda" build purge
  exit 0
fi

"${PREFIX}/bin/conda" build "recipes/${1}" \
                      --no-anaconda-upload \
                      --old-build-string   \
                      --channel conda-forge
