#!/usr/bin/env bash
#
# Convenience function to start a fenics-tue-builder docker container.

if [[ -z "${1}" ]]; then
  echo "Error: No recipe directory specified."
  exit 1
fi

cp "$(pwd)/recipes/conda_build_config.yaml" "$(pwd)/${1}/conda_build_config.yaml"
docker run -it --rm -v "$(pwd)/${1}:/recipe" fenics-tue-builder
