package:
  name: fenics-dijitso
  version: 2017.2.0

source:
  url: https://bitbucket.org/fenics-project/dijitso/downloads/dijitso-2017.2.0.tar.gz
  sha256: 05a893d17f8a50067d303b232e41592dce2840d6499677ad8b457ba58a679b58

build:
  number: 0

requirements:
  build:
    - python {{ python }}

  run:
    - python {{ python }}
    - subprocess32  # [py2k]
    - six
    - numpy

test:
  imports:
    - dijitso

  commands:
    - conda inspect linkages fenics-dijitso
