package:
  name: fenics-dijitso
  version: 2018.1.0

source:
  url: https://bitbucket.org/fenics-project/dijitso/downloads/dijitso-2018.1.0.tar.gz
  sha256: 2084ada1e7bd6ecec0999b15a17db98c72e26f1ccbf3fcbe240b1a035a1a2e64

build:
  number: 0

requirements:
  build:
    - python {{ python }}

  run:
    - python {{ python }}
    - subprocess32  # [py2k]
    - six
    - numpy

test:
  imports:
    - dijitso

  commands:
    - conda inspect linkages fenics-dijitso
