package:
  name: instant
  version: "2017.1.0"

source:
  url: https://bitbucket.org/fenics-project/instant/downloads/instant-2017.1.0.tar.gz
  sha256: 38f56bd9a583518fb023a90be6d09a114d74a36cacb91cbf50167002ac815ee7

build:
  number: 0
  string: py{{ CONDA_PY }}_tue_{{ PKG_BUILDNUM }}

requirements:
  build:
    - python {{ python }}
    - six
    - numpy
    - subprocess32  # [py2k]

  run:
    - python {{ python }}
    - six
    - numpy
    - subprocess32  # [py2k]

test:
  imports:
    - instant

  commands:
    - instant-clean
    - instant-showcache
