package:
  name: instant
  version: '2017.1.0'

source:
  fn: instant-2017.1.0.tar.gz
  url: https://bitbucket.org/fenics-project/instant/downloads/instant-2017.1.0.tar.gz
  sha256: 38f56bd9a583518fb023a90be6d09a114d74a36cacb91cbf50167002ac815ee7

requirements:
  build:
    - python
    - six
    - numpy

  run:
    - python
    - six
    - numpy

test:
  imports:
    - instant

  commands:
    - instant-clean
    - instant-showcache
