package:
  name: hdf5
  version: "1.8.18"

source:
  url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.18/src/hdf5-1.8.18.tar.gz
  sha256: cdb195ad8d9e6782acf24b2488061289f615628c2ccda8457b0a0c3fb7a8a063
  patches:
    - test_Makefile.in.patch

build:
  number: 0
  string: tue_{{ PKG_BUILDNUM }}
  detect_binary_files_with_prefix: True

requirements:
  build:
    - toolchain
    - libtool
    - cmake >=3.1
    - zlib >=1.2.11,<1.3
    - gcc
    - mpich

  run:
    - zlib >=1.2.11,<1.3

about:
  home: http://www.hdfgroup.org/HDF5/
  license: HDF5
  license_family: BSD
  license_file: COPYING
  summary: 'HDF5 is a data model, library, and file format for storing and managing data.'

extra:
  recipe-maintainers:
    - jakirkham
    - gillins
    - groutr
    - ocefpaf
    - astrofrog
    - marqh
    - echen
