package:
  name: fenics-python-components
  version: 2017.1.0

build:
  number: 0
  string: tue_py{{ CONDA_PY }}_{{ PKG_BUILDNUM }}

requirements:
  build:
    - nomkl
    - python {{ python }}

  run:
    - nomkl
    - python {{ python }}
    - subprocess32  # [py2k]
    - six
    - numpy
    - sympy

test:
  imports:
    - dijitso
    - ufl
    - instant
    - FIAT
    - ffc
