package:
  name: fenics-ufl
  version: 2017.2.0

source:
  url: https://bitbucket.org/fenics-project/ufl/downloads/ufl-2017.2.0.tar.gz
  sha256: 45562fcd29ceb2f2e37c44bc2552b8e6c5d76409f73526096d2bcdb7078cf99c

build:
  number: 0

requirements:
  build:
    - python {{ python }}

  run:
    - python {{ python }}
    - six
    - numpy

test:
  imports:
    - ufl

  commands:
    - conda inspect linkages fenics-ufl
