package:
  name: fenics-ufl
  version: 2018.1.0

source:
  url: https://bitbucket.org/fenics-project/ufl/downloads/ufl-2018.1.0.tar.gz
  sha256: ed191f5e0abfeb9922a68a6802f819e9cc6c50749472c01365319f66a5cfcbea

build:
  number: 0

requirements:
  build:
    - python {{ python }}

  run:
    - python {{ python }}
    - six
    - numpy

test:
  imports:
    - ufl

  commands:
    - conda inspect linkages fenics-ufl
