package:
  name: hdf5
  version: 1.8.19

source:
  url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.19/src/hdf5-1.8.19.tar.gz
  sha256: a4335849f19fae88c264fd0df046bc321a78c536b2548fc508627a790564dc38
  patches:
    - test_Makefile.in.patch

build:
  number: 0
  string: tue_{{ PKG_BUILDNUM }}
  detect_binary_files_with_prefix: True

requirements:
  build:
    - nomkl
    - gcc 4.8
    - libgcc 4.8
    - mpich

  run:
    - nomkl
    - gcc 4.8
    - libgcc 4.8
    - mpich

test:
  commands:
    - h5perf
    - h5perf_serial
