package:
  name: hdf5
  version: 1.8.20

source:
  url: https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-1.8.20.tar.bz2
  md5: 23078d57975903e9536d1e7b299cc39c

build:
  number: 3

requirements:
  build:
    - {{ openmpi }}
    - zlib

  run:
    - {{ openmpi }}
    - zlib

test:
  commands:
    - conda inspect linkages hdf5
