package:
  name: fenics
  version: "2017.1.0"

build:
  number: 0
  string: py{{ CONDA_PY }}_tue_{{ PKG_BUILDNUM }}

requirements:
  build:
    - python {{ python }}
    - dolfin 2017.1.* *tue*
    - mshr

  run:
    - python {{ python }}
    - dolfin 2017.1.* *tue*
    - mshr
