package:
  name: ufl
  version: '2017.1.0'

source:
  fn: ufl-2017.1.0.tar.gz
  url: https://bitbucket.org/fenics-project/ufl/downloads/ufl-2017.1.0.tar.gz
  sha256: af87fa10f492660e8dd9f5c820c03529e017b80bf2002da54b8234c56b8dda8f

requirements:
  build:
    - python {{ python }}
    - six
    - numpy

  run:
    - python
    - six
    - numpy

test:
  imports:
    - ufl
    - ufl.utils
    - ufl.finiteelement
    - ufl.core
    - ufl.corealg
    - ufl.algorithms

  commands:
    - ufl-version
    - ufl2py --help
