package:
  name: ufl
  version: "2017.1.0"

source:
  url: https://bitbucket.org/fenics-project/ufl/downloads/ufl-2017.1.0.tar.gz
  sha256: af87fa10f492660e8dd9f5c820c03529e017b80bf2002da54b8234c56b8dda8f

build:
  number: 0
  string: py{{ CONDA_PY }}_tue_{{ PKG_BUILDNUM }}

requirements:
  build:
    - python {{ python }}
    - six
    - numpy
    - subprocess32  # [py2k]

  run:
    - python {{ python }}
    - six
    - numpy
    - subprocess32  # [py2k]

test:
  imports:
    - ufl
    - ufl.utils
    - ufl.finiteelement
    - ufl.core
    - ufl.corealg
    - ufl.algorithms

  commands:
    - ufl-version
    - ufl2py --help
