package:
  name: fenics-mshr
  version: 2017.1.0

source:
  url: https://bitbucket.org/fenics-project/mshr/downloads/mshr-2017.1.0.tar.gz
  sha256: ec132dbc4c5469d8f828fc5c576c39c3d45cb231bd0b552585f9378c295ee689

build:
  number: 3

requirements:
  build:
    - python {{ python }}
    - openmpi 2.1.2
    - fenics-dolfin 2017.1.0
    - cmake
    - eigen
    - subprocess32  # [py2k]

  run:
    - python {{ python }}
    - fenics-dolfin 2017.1.0

test:
  source_files:
    - test/test-meshes.py
    - test/test-mesh-generation.py

  imports:
    - mshr

  commands:
    - conda inspect linkages fenics-mshr
