package:
  name: mshr
  version: 2017.1.0

source:
  url: https://bitbucket.org/fenics-project/mshr/downloads/mshr-2017.1.0.tar.gz
  sha256: ec132dbc4c5469d8f828fc5c576c39c3d45cb231bd0b552585f9378c295ee689

build:
  number: 0
  features:
    - tue

requirements:
  build:
    - cmake
    - dolfin            2017.1.0
    - python {{ python }}
    - swig              3.0.12   2

  run:
    - dolfin            2017.1.0
    - python {{ python }}

test:
  source_files:
    - test

  imports:
    - mshr

  commands:
    - conda inspect linkages mshr
