# This file created by conda-build 2.1.15
# meta.yaml template originally from:
# Origin b'https://github.intel.com/SAT/hdf5-recipe.git', commit b'ac7c420845ea9fcbc4f31a0fd53328da4921a97e'
# ------------------------------------------------

package:
    name: hdf5
    version: 1.8.17
source:
    fn: hdf5-1.8.17.tar.bz2
    md5: 34bd1afa5209259201a41964100d6203
    url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.17/src/hdf5-1.8.17.tar.bz2
build:
    features:
        - intel
    noarch: ''
    noarch_python: false
    number: '9'
    string: intel_9
requirements:
    build:
        - intelpython 2018.0.0 3
        - ncurses 5.9 10
        - expat 2.1.0 0
        - xz 5.2.2 intel_16
        - openssl 1.0.2k intel_3
        - curl 7.49.0 1
        - bzip2 1.0.6 intel_13
        - zlib 1.2.11 intel_3
        - cmake 3.6.3 0
    run:
        - intelpython
        - zlib 1.2.*
about:
    description: 'HDF5 is a data model, library, and file format for storing and managing

        data. It supports an unlimited variety of datatypes, and is designed for

        flexible and efficient I/O and for high volume and complex data. HDF5 is

        portable and is extensible, allowing applications to evolve in their use

        of HDF5. The HDF5 Technology suite includes tools and applications for

        managing, manipulating, viewing, and analyzing data in the HDF5 format.

        '
    dev_url: https://www.hdfgroup.org/HDF5/release/obtain5.html
    doc_url: https://www.hdfgroup.org/HDF5/doc/
    home: http://www.hdfgroup.org/HDF5/
    license: BSD-like
    license_family: BSD
    license_file: COPYING
    license_url: http://www.hdfgroup.org/ftp/HDF5/current/src/unpacked/COPYING
    summary: A data model, library, and file format for storing and managing data
extra:
    final: true
