package:
  name: gts
  version: 0.7.6

source:
  url: http://gts.sourceforge.net/tarballs/gts-snapshot-121130.tar.gz
  sha256: c23f72ab74bbf65599f8c0b599d6336fabe1ec2a09c19b70544eeefdc069b73b

build:
  number: 0
  string: tue_{{ PKG_BUILDNUM }}

requirements:
  build:
    - nomkl
    - gcc 4.8
    - libgcc 4.8
    - glib
    - pkgconfig

  run:
    - nomkl
    - glib
