package:
  name: dolfin
  version: 2017.1.0

source:
  url: https://bitbucket.org/fenics-project/dolfin/downloads/dolfin-2017.1.0.tar.gz
  sha256: ba793a2d41995d65ce4ee9e955e06342a6357174420b727cfde9fc6c70590e92

build:
  number: 0
  features:
    - tue

requirements:
  build:
    - boost             1.65.1
    - boost-cpp         1.65.1
    - cmake
    - doxygen           1.8.13   1
    - eigen             3.3.3    0
    - fenics-components 2017.1.0
    - hdf5              1.8.19   tue_0
    - petsc             3.8.1    tue_0
    - petsc4py          3.8.1
    - ply
    - python {{ python }}
    - sphinx
    - swig              3.0.12   2

  run:
    - boost             1.65.1
    - boost-cpp         1.65.1
    - eigen             3.3.3    0
    - fenics-components 2017.1.0
    - hdf5              1.8.19   tue_0
    - petsc             3.8.1    tue_0
    - petsc4py          3.8.1
    - ply
    - python {{ python }}

test:
  imports:
    - dolfin
    - fenics

  commands:
    - dolfin-version
    - fenics-version
    - conda inspect linkages dolfin
