package:
  name: mshr
  version: "2017.1.0"

source:
  url: https://bitbucket.org/fenics-project/mshr/downloads/mshr-2017.1.0.tar.gz
  sha256: ec132dbc4c5469d8f828fc5c576c39c3d45cb231bd0b552585f9378c295ee689
  patches:
    # Link boost_thread on macOS. Doesn't appear to be needed
    # on recent versions (10.12), but seems needed on Travis (Xcode 6.4, currently).
    - boost-thread.patch  # [osx]

build:
  number: 0
  string: py{{ CONDA_PY }}_tue_{{ PKG_BUILDNUM }}

requirements:
  build:
    - python {{ python }}
    - boost-cpp 1.64.*
    - cmake
    - gmp >=5.0.1,<7
    - mpfr 3.*
    - swig
    - toolchain
    - dolfin 2017.1.* *tue*

  run:
    - python {{ python }}
    - boost-cpp 1.64.*
    - gmp >=5.0.1,<7
    - mpfr 3.*
    - dolfin 2017.1.* *tue*

test:
  source_files:
    - test

  imports:
    - mshr

about:
  home: https://bitbucket.org/fenics-project/mshr
  license: GPL-3.0
  license_family: GPL3
  license_file: COPYING
  summary: mshr is the mesh generation component of FEniCS
  description: |
    mshr is the mesh generation component of FEniCS. It generates simplicial DOLFIN
    meshes in 2D and 3D from geometries described by Constructive Solid Geometry (CSG) or from
    surface files, utilizing CGAL and Tetgen as mesh generation backends.
  doc_url: http://fenics.readthedocs.io/projects/mshr
  dev_url: https://bitbucket.org/fenics-project/mshr

extra:
  recipe-maintainers:
    - minrk
    - jbweston
    - echen
