package:
  name: scalapack
  version: 2.0.2

source:
  url: http://www.netlib.org/scalapack/scalapack-2.0.2.tgz
  sha256: 0c74aeae690fe5ee4db7926f49c5d0bb69ce09eea75beb915e00bba07530395c

build:
  number: 4

requirements:
  build:
    - blacs 1.1
    - openmpi 2.1.2
    - openblas
