package:
  name: scalapack
  version: 2.0.2

source:
  url: http://www.netlib.org/scalapack/scalapack-2.0.2.tgz
  sha256: 0c74aeae690fe5ee4db7926f49c5d0bb69ce09eea75beb915e00bba07530395c

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - openmpi 2.1.2 h1c2f66e_4

  run:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - openmpi 2.1.2 h1c2f66e_4

test:
  requires:
    - blacs 1.1 h9ac9557_5
    - openblas

  source_files:
    - PBLAS
    - REDIST
    - TESTING
    - Makefile
    - TOOLS/LAPACK/icopy.f
