package:
  name: hypre
  version: 2.11.2

source:
  url: https://computation.llnl.gov/projects/hypre-scalable-linear-solvers-multigrid-methods/download/hypre-2.11.2.tar.gz
  sha256: 25b6c1226411593f71bb5cf3891431afaa8c3fd487bdfe4faeeb55c6fdfb269e

build:
  number: 2

requirements:
  build:
    - {{ openmpi }}
    - openblas

test:
  commands:
    - conda inspect linkages hypre
