{% set version = "2017.1.0" %}
{% set petsc_version = '3.7.*' %}
{% set swig_version = '3.0.12' %}

package:
  name: dolfin
  version: {{version}}

source:
  url: https://bitbucket.org/fenics-project/dolfin/downloads/dolfin-{{version}}.tar.gz
  sha256: ba793a2d41995d65ce4ee9e955e06342a6357174420b727cfde9fc6c70590e92

requirements:
  build:
    - python {{ python }}
    - pip
    - libgcc 4.8.*
    - gcc
    - boost 1.64.*
    - cmake
    - eigen
    - pkg-config
    - ptscotch
    - toolchain
    - zlib 1.2.*
    - mpich
    - petsc {{petsc_version}}
    - petsc4py {{petsc_version}}
    - slepc {{petsc_version}}
    - slepc4py {{petsc_version}}
    - swig {{swig_version}}
    - numpy 1.13.*
    - ply
    - six
    - subprocess32  # [py2k]
    - sympy
    - hdf5-parallel 1.8.18
    - ffc {{version}}
    - ufl {{version}}

  run:
    - python
    - setuptools
    - boost 1.64.*
    - cmake
    - eigen
    - gcc
    - mpich
    - petsc {{petsc_version}}
    - petsc4py {{petsc_version}}
    - slepc {{petsc_version}}
    - slepc4py {{petsc_version}}
    - pkg-config
    - ptscotch
    - zlib 1.2.*
    - ply
    - swig {{swig_version}}
    - numpy 1.13.*
    - six
    - subprocess32  # [py2k]
    - sympy
    - hdf5-parallel 1.8.18
    - ufl {{version}}
    - ffc {{version}}
    - instant {{version}}

test:
  files:
    - test_hdf5_parallel.py

  imports:
    - dolfin
    - fenics

  commands:
    - fenics-version

about:
  home: http://www.fenicsproject.org
  license: LGPL 3.0
  license_file: COPYING.LESSER
  summary: 'FEniCS is a collection of free software for automated, efficient solution of differential equations'

  description: |
    FEniCS is a collection of free software for automated, efficient solution of differential equations
    (<http://fenicsproject.org>). It provides C++ and Python interfaces, and creates effecient solvers via
    expression of finite variational statements in a domain-specific language that are transformed and
    just-in-time compiled into efficient implementations.
  doc_url: http://fenics.readthedocs.io/
  dev_url: https://bitbucket.org/fenics-project/

extra:
  recipe-maintainers:
    - garth-wells
    - johannesring
    - mikaem
    - minrk
    - echen
