package:
  name: fiat
  version: "2017.1.0"

source:
  url: https://bitbucket.org/fenics-project/fiat/downloads/fiat-2017.1.0.tar.gz
  sha256: d4288401ad16c4598720f9db0810a522f7f0eadad35d8211bac7120bce5fde94

build:
  number: 0
  string: py{{ CONDA_PY }}_tue_{{ PKG_BUILDNUM }}

requirements:
  build:
    - python {{ python }}
    - six
    - numpy
    - sympy
    - subprocess32  # [py2k]

  run:
    - python {{ python }}
    - six
    - numpy
    - sympy
    - subprocess32  # [py2k]

test:
  imports:
    - FIAT
