package:
  name: fenics
  version: 2017.2.0

build:
  number: 4

requirements:
  build:
    - python {{ python }}

  run:
    - python {{ python }}
    - fenics-dolfin 2017.2.0 py*_1
    - fenics-mshr 2017.2.0
    - fenics-dijitso 2017.2.0
    - matplotlib
    - pandas
    - scipy
    - eigen

test:
  imports:
    - dolfin
    - fenics
    - mshr

  commands:
    - conda inspect linkages fenics
