package:
  name: fenics
  version: 2018.1.0

build:
  number: 0

requirements:
  build:
    - python {{ python }}

  run:
    - python {{ python }}
    - fenics-dolfin 2018.1.0
    - fenics-mshr 2018.1.0
    - fenics-dijitso 2018.1.0
    - matplotlib
    - pandas
    - scipy
    - eigen
    - cmake

test:
  imports:
    - dolfin
    - mshr

  commands:
    - conda inspect linkages fenics
