package:
  name: fenics
  version: 2017.1.0

build:
  number: 0
  features:
    - tue

requirements:
  build:
    - python {{ python }}

  run:
    - dolfin              2017.1.0
    - mshr                2017.1.0
    - python {{ python }}
    - tue

test:
  imports:
    - dolfin
    - fenics
    - mshr

  commands:
    - conda inspect linkages fenics
