package:
  name: fenics
  version: 2017.1.0

build:
  number: 0
  string: tue_py{{ CONDA_PY }}_{{ PKG_BUILDNUM }}

requirements:
  run:
    - nomkl
    - python {{ python }}
    - dolfin 2017.1.0 tue*
    - mshr 2017.1.0 tue*

test:
  imports:
    - dolfin
    - fenics
    - mshr
