package:
  name: fenics
  version: 2017.1.0

build:
  number: 2

requirements:
  build:
    - python {{ python }}

  run:
    - python {{ python }}
    - fenics-dolfin 2017.1.0
    - fenics-mshr 2017.1.0
    - fenics-dijitso 2017.1.0
    - matplotlib
    - pandas
    - scipy

test:
  imports:
    - dolfin
    - fenics
    - mshr

  commands:
    - conda inspect linkages fenics
