package:
  name: fenics
  version: 2017.1.0

build:
  number: 1

requirements:
  build:
    - python {{ python }}

  run:
    - python {{ python }}
    - {{ dolfin }}
    - {{ mshr }}
    - {{ dijitso }}
    - matplotlib
    - pandas
    - scipy

test:
  imports:
    - dolfin
    - fenics
    - mshr

  commands:
    - conda inspect linkages fenics
