package:
  name: scotch
  version: 6.0.4

source:
  url: https://gforge.inria.fr/frs/download.php/file/34618/scotch_6.0.4.tar.gz
  sha256: f53f4d71a8345ba15e2dd4e102a35fd83915abf50ea73e1bf6efe1bc2b4220c7

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - openmpi 2.1.2 h1c2f66e_4
    - bison
    - zlib

  run:
    - {{ compiler('c') }}
    - openmpi 2.1.2 h1c2f66e_4
    - zlib

test:
  source_files:
    - src/check
    - src/libscotch/*.h

  commands:
    - conda inspect linkages scotch