package:
  name: fenics-instant
  version: 2017.2.0

source:
  url: https://bitbucket.org/fenics-project/instant/downloads/instant-2017.2.0.tar.gz
  sha256: be24f162fd1a89b82fae002db8df0b4f111fd50db83d78c0c121015c02e45b7b

build:
  number: 0

requirements:
  build:
    - python {{ python }}

  run:
    - python {{ python }}
    - six

test:
  imports:
    - instant

  commands:
    - conda inspect linkages fenics-instant
