package:
  name: mumps
  version: 5.0.2

source:
  url: http://mumps.enseeiht.fr/MUMPS_5.1.2.tar.gz
  sha256: eb345cda145da9aea01b851d17e54e7eef08e16bfa148100ac1f7f046cd42ae9

build:
  number: 0

requirements:
  build:
    - gcc         4.8.5  7
    - libgcc      4.8.5  2
    - libgfortran 3.0.0  1
    - mpich       3.2    5
    - openblas    0.2.20 6
    - ptscotch    6.0.4  4
    - scalapack   2.0.2  1
    - scotch      6.0.4  3

test:
  commands:
    - conda inspect linkages mumps
