package:
  name: mumps
  version: 5.0.2

source:
  url: http://mumps.enseeiht.fr/MUMPS_5.0.2.tar.gz
  sha256: 77292b204942640256097a3da482c2abcd1e0d5a74ecd1d4bab0f5ef6e60fe45

build:
  number: 0
  string: tue_{{ PKG_BUILDNUM }}

requirements:
  build:
    - nomkl
    - gcc 4.8
    - libgcc 4.8
    - mpich
    - scotch 6.0.4
    - ptscotch 6.0.4
    - openblas
    - scalapack

  run:
    - nomkl

test:
  commands:
    - test -f "${PREFIX}/lib/libzmumps.a"
    - test -f "${PREFIX}/lib/libcmumps.a"
    - test -f "${PREFIX}/lib/libdmumps.a"
    - test -f "${PREFIX}/lib/libsmumps.a"
    - test -f "${PREFIX}/lib/libmumps_common.a"
    - test -f "${PREFIX}/lib/libpord.a"
    - test -f "${PREFIX}/include/dmumps_struc.h"
    - test -f "${PREFIX}/include/zmumps_struc.h"
    - test -f "${PREFIX}/include/cmumps_struc.h"
    - test -f "${PREFIX}/include/smumps_struc.h"
