package:
  name: mumps
  version: 5.0.2

source:
  url: http://mumps.enseeiht.fr/MUMPS_5.0.2.tar.gz
  sha256: 77292b204942640256097a3da482c2abcd1e0d5a74ecd1d4bab0f5ef6e60fe45

build:
  number: 0
  features:
    - tue

requirements:
  build:
    - gcc         4.8.5  7
    - libgcc      4.8.5  2
    - libgfortran 3.0.0  1
    - mpich       3.2    5
    - openblas    0.2.20 6
    - ptscotch    6.0.4  4
    - scalapack   2.0.2  1
    - scotch      6.0.4  3
    - zlib        1.2.11 0

  run:
    - tue

test:
  source_files:
    - examples

  commands:
    - conda inspect linkages mumps
