package:
  name: mumps
  version: 5.1.2

source:
  url: http://mumps.enseeiht.fr/MUMPS_5.1.2.tar.gz
  sha256: eb345cda145da9aea01b851d17e54e7eef08e16bfa148100ac1f7f046cd42ae9

build:
  number: 3

requirements:
  build:
    - {{ openmpi }}
    - {{ blacs }}
    - {{ scotch }}
    - {{ scalapack }}
    - openblas

test:
  commands:
    - conda inspect linkages mumps
