package:
    name: binutils_haswell_haswell_{{ target_platform }}
    version: 7.2.0

build:
    number: 0

requirements:
    build:
        - gcc_impl_{{ target_platform }}
    run:
        - binutils_impl_{{ target_platform }} 2.28.1.*