package:
  name: fenics-components
  version: 2017.1.0

build:
  number: 0
  features:
    - tue

requirements:
  build:
    - python {{ python }}

  run:
    - libgfortran 3.0.0  1
    - numpy
    - openblas    0.2.20 6
    - python {{ python }}
    - six
    - subprocess32 # [py2k]
    - sympy
    - tue

test:
  imports:
    - dijitso
    - ufl
    - instant
    - FIAT
    - ffc

  commands:
    - conda inspect linkages fenics-components
