package:
  name: fenics-ffc
  version: 2018.1.0

source:
  url: https://bitbucket.org/fenics-project/ffc/downloads/ffc-2018.1.0.tar.gz
  sha256: c5a6511693106d1cd2fc013148d0cd01cd1b99fc65dab461ca0b95851a9ea271

build:
  number: 0

requirements:
  build:
    - python {{ python }}

  run:
    - python {{ python }}
    - fenics-ufl 2018.1.0
    - fenics-fiat 2018.1.0
    - numpy

test:
  imports:
    - ffc

  commands:
    - conda inspect linkages fenics-ffc
