package:
  name: fenics-ffc
  version: 2017.2.0

source:
  url: https://bitbucket.org/fenics-project/ffc/downloads/ffc-2017.2.0.tar.gz
  sha256: c7e52c552bb6bf4748ba27d63725eb79ffba7260a6052a6e5f3c3e0e6b0a7279

build:
  number: 0

requirements:
  build:
    - python {{ python }}

  run:
    - python {{ python }}
    - fenics-ufl 2017.2.0
    - fenics-fiat 2017.2.0
    - numpy

test:
  imports:
    - ffc

  commands:
    - conda inspect linkages fenics-ffc
