package:
  name: openblas
  version: 0.2.20

source:
  url: http://github.com/xianyi/OpenBLAS/archive/v0.2.20.tar.gz
  sha256: 5ef38b15d9c652985774869efd548b8e3e972e1e99475c673b25537ed7bcf394

build:
  number: 0

requirements:
  build:
    - gcc_linux-64

  run:
    - gcc_linux-64

test:
  commands:
    - conda inspect linkages openblas
