{% set build_number = '0' %}

{% set python_string = ''.join(['py'] + python.split('.')[:2]) %}

package:
  name: fenics-python-packages
  version: 2017.1.0

source:
  - url: https://bitbucket.org/fenics-project/dijitso/downloads/dijitso-2017.1.0.tar.gz
    sha256: ef23952539d349fbd384d41302abc94413d485ca7e8c29e8a0debc2aadaf8657
    folder: dijitso
  - url: https://bitbucket.org/fenics-project/ufl/downloads/ufl-2017.1.0.tar.gz
    sha256: af87fa10f492660e8dd9f5c820c03529e017b80bf2002da54b8234c56b8dda8f
    folder: ufl
  - url: https://bitbucket.org/fenics-project/instant/downloads/instant-2017.1.0.tar.gz
    sha256: 38f56bd9a583518fb023a90be6d09a114d74a36cacb91cbf50167002ac815ee7
    folder: instant
  - url: https://bitbucket.org/fenics-project/fiat/downloads/fiat-2017.1.0.tar.gz
    sha256: d4288401ad16c4598720f9db0810a522f7f0eadad35d8211bac7120bce5fde94
    folder: fiat
  - url: https://bitbucket.org/fenics-project/ffc/downloads/ffc-2017.1.0.tar.gz
    sha256: 2073c4d8f998798a3b0a8a371e74d9848f0e52933cf5f35cee21e82ab3fe87b3
    folder: ffc

build:
  number: {{ build_number }}
  string: {{ python_string }}_{{ build_number }}

requirements:
  build:
    - python {{ python }}
    - six
    - numpy
    - sympy
    - subprocess32  # [py2k]

  run:
    - python {{ python }}
    - six
    - numpy
    - sympy
    - subprocess32  # [py2k]

test:
  imports:
    - dijitso
    - ufl
    - ufl.utils
    - ufl.finiteelement
    - ufl.core
    - ufl.corealg
    - ufl.algorithms
    - instant
    - FIAT
    - ffc
    - ffc.backends
    - ffc.backends.dolfin
    - ffc.backends.ufc
    - ffc.errorcontrol
    - ffc.quadrature
    - ffc.tensor

  commands:
    - ufl-version
    - ufl2py --help
    - instant-clean
    - instant-showcache
    - ffc --help
