package:
  name: fenics-dolfin
  version: 2017.1.0

source:
  url: https://bitbucket.org/fenics-project/dolfin/downloads/dolfin-2017.1.0.tar.gz
  sha256: ba793a2d41995d65ce4ee9e955e06342a6357174420b727cfde9fc6c70590e92

build:
  number: 3

requirements:
  build:
    - python {{ python }}
    - openmpi 2.1.2
    - hypre 2.11.2
    - mumps 5.1.2
    - scotch 6.0.4
    - scalapack 2.0.2
    - blacs 1.1
    - hdf5 1.8.20
    - fenics-ffc 2017.1.0
    - petsc 3.8.1
    - openblas
    - boost
    - cmake
    - eigen
    - ply
    - swig
    - pthread-stubs

  run:
    - python {{ python }}
    - openmpi 2.1.2
    - hdf5 1.8.20
    - fenics-ffc 2017.1.0
    - fenics-ufl 2017.1.0
    - fenics-instant 2017.1.0
    - petsc 3.8.1
    - openblas
    - boost
    - numpy
    - ply
    - swig

test:
  imports:
    - dolfin
    - fenics

  commands:
    - conda inspect linkages fenics-dolfin
