package:
  name: fenics-dolfin
  version: 2018.1.0

source:
  url: https://bitbucket.org/fenics-project/dolfin/downloads/dolfin-2018.1.0.tar.gz
  sha256: 5d1836df4dcc1d55f63ecc20635305a6d5b39cbfc63584b43ec2568452dc5e71

build:
  number: 0

requirements:
  build:
    - python {{ python }}
    - openmpi 2.1.2
    - hypre 2.11.2
    - mumps 5.1.2 6
    - scotch 6.0.4 7
    - scalapack 2.0.2
    - blacs 1.1
    - hdf5 1.8.20
    - fenics-ffc 2018.1.0
    - petsc 3.8.1 5
    - openblas
    - boost 1.67.0
    - cmake
    - eigen
    - ply
    - pthread-stubs
    - petsc4py 3.8.1
    - pybind11 2.2.3
    - sympy 1.1.*
    - pkg-config
    - pkgconfig
    - fenics-dijitso 2018.1.0
    - fenics-fiat 2018.1.0
    - fenics-ffc 2018.1.0
    - fenics-ufl 2018.1.0

  run:
    - python {{ python }}
    - openmpi 2.1.2
    - hdf5 1.8.20
    - fenics-dijitso 2018.1.0
    - fenics-fiat 2018.1.0
    - fenics-ffc 2018.1.0
    - fenics-ufl 2018.1.0
    - petsc 3.8.1
    - openblas
    - boost 1.67.0
    - numpy
    - ply
    - petsc4py 3.8.1
    - pkg-config
    - pkgconfig
    - pybind11 2.2.3
    - sympy 1.1.*

test:
  imports:
    - dolfin

  commands:
    - conda inspect linkages fenics-dolfin
