package:
  name: fenics-dolfin
  version: 2017.2.0

source:
  url: https://bitbucket.org/fenics-project/dolfin/downloads/dolfin-2017.2.0.tar.gz
  sha256: da548ed983c84201be494daa6fe12cd028936dfbaef181a8bced239f5d68e8bc

build:
  number: 1

requirements:
  build:
    - python {{ python }}
    - openmpi 2.1.2
    - hypre 2.11.2
    - mumps 5.1.2
    - scotch 6.0.4
    - scalapack 2.0.2
    - blacs 1.1
    - hdf5 1.8.20
    - fenics-ffc 2017.2.0
    - petsc 3.8.1
    - openblas
    - boost
    - cmake
    - eigen
    - ply
    - swig
    - pthread-stubs
    - petsc4py 3.8.1

  run:
    - python {{ python }}
    - openmpi 2.1.2
    - hdf5 1.8.20
    - fenics-ffc 2017.2.0
    - fenics-ufl 2017.2.0
    - fenics-instant 2017.2.0
    - petsc 3.8.1
    - openblas
    - boost
    - numpy
    - ply
    - swig
    - petsc4py 3.8.1

test:
  imports:
    - dolfin
    - fenics

  commands:
    - conda inspect linkages fenics-dolfin
