package:
  name: tue
  version: "1.0"

build:
  number: 0
  string: {{ march }}_{{ PKG_BUILDNUM }}
  track_features:
    - {{ march }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}

  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}