package:
  name: openmpi
  version: 2.1.2

source:
  url: https://www.open-mpi.org/software/ompi/v2.1/downloads/openmpi-2.1.2.tar.bz2
  md5: ff2e55cc529802e7b0738cf87acd3ee4

build:
  number: 6

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - libgcc-ng

  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - libgcc-ng

test:
  source_files:
    - examples

  commands:
    - conda inspect linkages openmpi
