package:
  name: petsc
  version: 3.8.1

source:
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.8.1.tar.gz
  sha256: fdc94525422c41ed617b38d09723bb27c6dbf4831c4c6cc1e27850e60788ccfa

build:
  number: 0

requirements:
  build:
    - {{ openmpi }}
    - {{ blacs }}
    - {{ hypre }}
    - {{ scotch }}
    - {{ scalapack }}
    - {{ mumps }}

  run:
    - {{ openmpi }}
    - openblas

test:
  requires:
    - libgcc-ng

  commands:
    - conda inspect linkages petsc
