package:
  name: petsc
  version: 3.8.1

source:
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.8.1.tar.gz
  sha256: fdc94525422c41ed617b38d09723bb27c6dbf4831c4c6cc1e27850e60788ccfa

build:
  number: 4

requirements:
  build:
    - openmpi 2.1.2
    - blacs 1.1
    - hypre 2.11.2
    - scotch 6.0.4
    - scalapack 2.0.2
    - mumps 5.1.2
    - openblas

  run:
    - openmpi 2.1.2
    - libgcc-ng
    - openblas

test:
  commands:
    - conda inspect linkages petsc
